Repository lenskit/lkpy, pull requests merged in 2020-12, with the labels that each got.

#211 Test on multiple BLAS versions
  .github/workflows/test-suite.yml
Labels: build

#212 Add keystone test depending on others
  .github/workflows/test-suite.yml
  .gitignore
  conftest.py
  pytest.ini
  utils/all-power.py
Labels: batch

#214 Allow scipy='coo' in sparse_ratings
  lenskit/matrix/__init__.py
  tests/test_matrix.py
Labels: internals
