Repository lenskit/lkpy, pull requests merged in 2024-03, with the labels that each got.

#358 Properly clone tuples
  lenskit/util/__init__.py
  tests/test_bias.py
  tests/test_util.py
Labels: bug

#366 Expand build matrix for Apple Silicon & MacOS vanilla Python builds
  .github/workflows/test.yml
Labels: build

#369 Documentation fix for Recall and Hit
  lenskit/metrics/topn.py
Labels: evaluation
