Repository lenskit/lkpy, pull requests merged in 2024-12, with the labels that each got.

#541 Use bias model as default fallback for prediction
  lenskit/lenskit/pipeline/common.py
Labels: pipeline

#542 Fix subprocess logging
  lenskit/lenskit/logging/monitor.py
  lenskit/lenskit/logging/processors.py
  lenskit/lenskit/logging/worker.py
  lenskit/lenskit/parallel/pool.py
  lenskit/lenskit/parallel/worker.py
Labels: internals

#543 Correct item list collection merging and implement bulk analysis grouped summaries
  lenskit/lenskit/data/collection.py
  lenskit/lenskit/metrics/bulk.py
  lenskit/tests/data/test_collection.py
  lenskit/tests/eval/test_bulk_metrics.py
Labels: evaluation, data

#544 Fix feedback setting name for item KNN
  lenskit/lenskit/knn/item.py
  lenskit/tests/models/test_knn_item_item.py
Labels: bug, components

#548 Add resource measurement for “tasks”
  conftest.py
  lenskit/lenskit/logging/monitor.py
  lenskit/lenskit/logging/resource.py
  lenskit/lenskit/logging/tasks.py
  lenskit/lenskit/logging/worker.py
  lenskit/lenskit/parallel/pool.py
  lenskit/tests/utils/test_task_logging.py
Labels: internals

#550 Test with Python 3.13 and Numpy 2.x
  .github/workflows/test.yml
  lenskit-implicit/pyproject.toml
  lenskit/pyproject.toml
  lenskit/tests/pipeline/test_types.py
  pixi.lock
  pixi.toml
  workflows/lib/defs.ts
  workflows/test.ts
  workflows/test/common.ts
  workflows/test/spec.ts
Labels: build, internals

#553 Small user-user performance tweaks
  lenskit/lenskit/knn/user.py
  lenskit/lenskit/math/sparse.py
  lenskit/tests/models/test_knn_user_user.py
Labels: components, performance

#554 Slightly tweak ALS solving for clarity and performance
  lenskit/lenskit/als/_explicit.py
  lenskit/lenskit/math/solve.py
Labels: components

#556 Add recommend and predict utility functions
  docs/api/index.rst
  docs/api/operations.rst
  docs/guide/migrating.rst
  docs/guide/pipeline.rst
  lenskit/lenskit/__init__.py
  lenskit/lenskit/operations.py
  lenskit/tests/basic/test_bias.py
Labels: pipeline

#558 Document log configuration and support environment variables
  docs/_static/css/custom.css
  docs/conf.py
  docs/guide/index.rst
  docs/guide/logging.rst
  lenskit/lenskit/logging/__init__.py
  lenskit/lenskit/logging/config.py
  lenskit/lenskit/logging/processors.py
  pixi.lock
Labels: internals

#564 Add a Gini coefficient function
  lenskit/lenskit/stats.py
  lenskit/tests/math/test_gini.py
Labels: internals

#565 Fix item-item bug with unknown items
  lenskit/lenskit/knn/item.py
  lenskit/tests/models/test_knn_item_item.py
Labels: bug

#493 feat: Add TimeBoundedPopScore for time-bounded popularity
  lenskit/lenskit/basic/popularity.py
  lenskit/tests/basic/test_time_bounded_popular.py
Labels: enhancement, components

#570 Add documentation for queries and principles
  docs/api/data.rst
  docs/api/splitting.rst
  docs/evaluation/topn-metrics.rst
  docs/guide/index.rst
  docs/guide/item-lists.rst
  docs/guide/principles.rst
  docs/guide/queries.rst
  lenskit/lenskit/data/collection.py
  lenskit/lenskit/splitting/temporal.py
  lenskit/tests/data/test_collection.py
Labels: docs

#572 Update load_movielens_df to return new standard field names
  lenskit-hpf/tests/test_hpf.py
  lenskit/lenskit/data/movielens.py
  lenskit/tests/basic/test_bias.py
  lenskit/tests/data/test_bulk.py
  lenskit/tests/data/test_dataset_ids.py
  lenskit/tests/data/test_dataset_lazy.py
  lenskit/tests/data/test_dataset_log.py
  lenskit/tests/data/test_dataset_matrix.py
  lenskit/tests/data/test_dataset_stats.py
  lenskit/tests/eval/test_bulk_metrics.py
  lenskit/tests/models/test_als_explicit.py
  lenskit/tests/models/test_knn_item_item.py
  lenskit/tests/models/test_knn_user_user.py
  lenskit/tests/splitting/test_split_users.py
Labels: data

#573 Improve pipeline logging and builder API
  lenskit/lenskit/basic/bias.py
  lenskit/lenskit/logging/__init__.py
  lenskit/lenskit/pipeline/__init__.py
  lenskit/lenskit/pipeline/common.py
  lenskit/lenskit/pipeline/components.py
  lenskit/lenskit/pipeline/runner.py
  lenskit/tests/basic/test_composite.py
Labels: enhancement, pipeline

#575 Move LensKit test support into lenskit.testing package
  conftest.py
  docs/api/index.rst
  lenskit-funksvd/tests/test_funksvd.py
  lenskit-implicit/tests/test_implicit.py
  lenskit/lenskit/als/_implicit.py
  lenskit/lenskit/testing/__init__.py
  lenskit/lenskit/testing/_arrays.py
  lenskit/lenskit/testing/_movielens.py
  lenskit/lenskit/util/test.py
  lenskit/tests/basic/test_candidates.py
  lenskit/tests/basic/test_composite.py
  lenskit/tests/basic/test_history.py
  lenskit/tests/basic/test_popular.py
  lenskit/tests/basic/test_random.py
  lenskit/tests/basic/test_softmax.py
  lenskit/tests/basic/test_topn.py
  lenskit/tests/batch/test_batch_pipeline.py
  lenskit/tests/data/test_collection.py
  lenskit/tests/data/test_dataset_ids.py
  lenskit/tests/data/test_dataset_lazy.py
  lenskit/tests/data/test_dataset_log.py
  lenskit/tests/data/test_dataset_matrix.py
  lenskit/tests/data/test_dataset_stats.py
  lenskit/tests/data/test_itemlist.py
  lenskit/tests/eval/test_bulk_metrics.py
  lenskit/tests/eval/test_rank_hit.py
  lenskit/tests/eval/test_rank_mrr.py
  lenskit/tests/eval/test_rank_precision.py
  lenskit/tests/eval/test_rank_rbp.py
  lenskit/tests/eval/test_rank_recall.py
  lenskit/tests/models/test_als_explicit.py
  lenskit/tests/models/test_als_implicit.py
  lenskit/tests/models/test_knn_item_item.py
  lenskit/tests/models/test_knn_user_user.py
  lenskit/tests/parallel/test_parallel.py
  lenskit/tests/parallel/test_shm_serialize.py
  lenskit/tests/utils/test_matrix.py
  lenskit/tests/utils/test_matrix_rows.py
Labels: build

#577 Add user/item vocab options and subsetting to from_interactions_df
  lenskit/lenskit/data/convert.py
  lenskit/tests/data/test_dataset_convert.py
Labels: data

#576 Implement and use common component test suites
  lenskit-funksvd/lenskit/funksvd.py
  lenskit-funksvd/tests/test_funksvd.py
  lenskit-hpf/lenskit/hpf.py
  lenskit-hpf/tests/test_hpf.py
  lenskit-implicit/tests/test_implicit.py
  lenskit-sklearn/lenskit/sklearn/svd.py
  lenskit-sklearn/tests/test_svd.py
  lenskit/lenskit/als/_explicit.py
  lenskit/lenskit/als/_implicit.py
  lenskit/lenskit/data/__init__.py
  lenskit/lenskit/knn/item.py
  lenskit/lenskit/knn/user.py
  lenskit/lenskit/testing/__init__.py
  lenskit/lenskit/testing/_components.py
  lenskit/lenskit/testing/_markers.py
  lenskit/lenskit/testing/_movielens.py
  lenskit/tests/basic/test_bias.py
  lenskit/tests/basic/test_composite.py
  lenskit/tests/basic/test_popular.py
  lenskit/tests/basic/test_softmax.py
  lenskit/tests/models/test_als_explicit.py
  lenskit/tests/models/test_als_implicit.py
  lenskit/tests/models/test_knn_item_item.py
  lenskit/tests/models/test_knn_user_user.py
Labels: components, internals

#578 Accelerate item-item k-NN algorithms
  lenskit/lenskit/knn/item.py
  lenskit/lenskit/util/torch.py
  lenskit/tests/models/test_knn_item_item.py
Labels: components, performance

#579 Modest user-KNN speedups + item KNN logging
  lenskit/lenskit/knn/item.py
  lenskit/lenskit/knn/user.py
Labels: components

#580 Add basic_logging function and use it in the GettingStarted notebook
  docs/guide/GettingStarted.ipynb
  docs/guide/logging.rst
  lenskit/lenskit/logging/__init__.py
  lenskit/lenskit/logging/config.py
Labels: docs, internals

#582 Add predict_pipeline, remove data.bulk module, and clean up batch functions
  lenskit-funksvd/tests/test_funksvd.py
  lenskit/lenskit/batch/__init__.py
  lenskit/lenskit/batch/_predict.py
  lenskit/lenskit/batch/_recommend.py
  lenskit/lenskit/batch/_runner.py
  lenskit/lenskit/data/bulk.py
  lenskit/lenskit/pipeline/common.py
  lenskit/tests/batch/test_batch_pipeline.py
  lenskit/tests/data/test_bulk.py
  lenskit/tests/models/test_knn_item_item.py
  lenskit/tests/models/test_knn_user_user.py
Labels: internals

#583 Implement a proxy logger that suppresses debug & info messages by default
  docs/guide/GettingStarted.ipynb
  docs/guide/logging.rst
  lenskit/lenskit/data/movielens.py
  lenskit/lenskit/knn/item.py
  lenskit/lenskit/knn/user.py
  lenskit/lenskit/logging/__init__.py
  lenskit/lenskit/logging/_proxy.py
  lenskit/lenskit/logging/monitor.py
  lenskit/lenskit/logging/progress/_rich.py
  lenskit/lenskit/logging/resource.py
  lenskit/lenskit/logging/tasks.py
  lenskit/lenskit/logging/worker.py
  lenskit/lenskit/parallel/pool.py
  lenskit/lenskit/parallel/worker.py
  lenskit/lenskit/pipeline/__init__.py
  lenskit/lenskit/testing/_movielens.py
Labels: internals
