Repository lenskit/lkpy, pull requests merged in 2025-03, with the labels that each got.

#649 Fix ItemList.from_arrow when nullable column
  src/lenskit/data/items.py
  tests/data/test_itemlist.py
Labels: data

#650 Make sure components work with forward references to configuration types
  src/lenskit/pipeline/components.py
  tests/pipeline/test_component_config.py
Labels: pipeline

#651 Move lenskit.util code into more logical places
  .github/workflows/test.yml
  docs/api/index.rst
  docs/guide/conventions.rst
  docs/guide/performance.rst
  pixi.lock
  pyproject.toml
  src/lenskit/batch/_runner.py
  src/lenskit/cli/doctor.py
  src/lenskit/funksvd.py
  src/lenskit/knn/item.py
  src/lenskit/knn/user.py
  src/lenskit/logging/__init__.py
  src/lenskit/logging/_console.py
  src/lenskit/logging/resource.py
  src/lenskit/logging/stopwatch.py
  src/lenskit/sklearn/svd.py
  src/lenskit/torch.py
  src/lenskit/util/__init__.py
  tests/basic/test_bias.py
  tests/models/test_knn_item_item.py
  tests/models/test_knn_user_user.py
  tests/utils/test_stopwatch.py
  workflows/test/environment.ts
Labels: internals

#653 Add meaningful error on duplicate metrics
  src/lenskit/metrics/bulk.py
  tests/eval/test_bulk_metrics.py
Labels: evaluation

#655 Speed up implicit bridge scoring performance
  src/lenskit/implicit.py
Labels: components

#658 Use counts instead of ratings in HPF
  docs/releases/2025.rst
  src/lenskit/data/relationships.py
  src/lenskit/hpf.py
  tests/data/test_dataset_matrix.py
Labels: components

#660 Support dataframe-format test data for batch recommendation
  docs/releases/2025.rst
  src/lenskit/batch/__init__.py
  src/lenskit/batch/_runner.py
  src/lenskit/testing/_movielens.py
  tests/batch/test_batch_pipeline.py
Labels: batch

#661 Add PipelineCache to allow pipeline builders to cache component instances
  docs/api/pipeline.rst
  src/lenskit/pipeline/__init__.py
  src/lenskit/pipeline/builder.py
  src/lenskit/pipeline/cache.py
  tests/pipeline/test_cache.py
  tests/pipeline/test_modify_pipeline.py
Labels: pipeline

#664 Only warn once for users with missing test items in analysis
  src/lenskit/metrics/bulk.py
Labels: evaluation

#666 Simplify test workfow
  .copier-answers.yml
  .github/workflows/test.yml
  deno.jsonc
  deno.lock
  justfile
  pixi.lock
  pixi.toml
  pyproject.toml
  workflows/lib/checkout.ts
  workflows/lib/defs.ts
  workflows/lib/script.ts
  workflows/render.ts
  workflows/test.ts
  workflows/test/common.ts
  workflows/test/conda.ts
  workflows/test/data.ts
  workflows/test/environment.ts
  workflows/test/results.ts
  workflows/test/spec.ts
  workflows/test/test-eval.ts
  workflows/test/test-examples.ts
  workflows/test/vanilla.ts
Labels: build

#668 Add flexible Torch matrix factorizer
  docs/lenskit.bib
  docs/releases/2025.rst
  src/lenskit/cli/doctor.py
  src/lenskit/data/builder.py
  src/lenskit/data/collection/__init__.py
  src/lenskit/data/collection/_base.py
  src/lenskit/data/collection/_list.py
  src/lenskit/data/mtarray.py
  src/lenskit/data/relationships.py
  src/lenskit/flexmf/__init__.py
  src/lenskit/flexmf/_base.py
  src/lenskit/flexmf/_explicit.py
  src/lenskit/flexmf/_implicit.py
  src/lenskit/flexmf/_model.py
  src/lenskit/flexmf/_training.py
  src/lenskit/pipeline/cache.py
  src/lenskit/stochastic/__init__.py
  src/lenskit/stochastic/_ranker.py
  src/lenskit/testing/_components.py
  src/lenskit/util.py
  tests/data/test_sparse_select.py
  tests/flexmf/test_flexmf_explicit.py
  tests/flexmf/test_flexmf_implicit.py
Labels: components

#676 Limit test users to only have users who had item in the train data.
  src/lenskit/splitting/temporal.py
  tests/splitting/test_split_temporal_filter.py
Labels: evaluation

#677 Add train and recommend commands to the CLI
  .gitignore
  pixi.lock
  pyproject.toml
  src/lenskit/batch/_runner.py
  src/lenskit/cli/__init__.py
  src/lenskit/cli/recommend.py
  src/lenskit/cli/train.py
  src/lenskit/data/dataset.py
  src/lenskit/data/entities.py
  src/lenskit/data/items.py
  src/lenskit/logging/config.py
  src/lenskit/logging/processors.py
  src/lenskit/logging/stopwatch.py
  src/lenskit/pipeline/common.py
Labels: cli

#680 Improve NumPy -> Torch conversions for read-only data
  src/lenskit/als/_explicit.py
  src/lenskit/basic/bias.py
  src/lenskit/data/attributes.py
  src/lenskit/data/mtarray.py
  src/lenskit/data/relationships.py
  src/lenskit/flexmf/_base.py
  src/lenskit/knn/item.py
  src/lenskit/knn/user.py
  src/lenskit/math/sparse.py
  src/lenskit/torch.py
  tests/utils/test_matrix_rows.py
  tests/utils/test_torch_util.py
Labels: internals

#681 Improve progress bar update API
  src/lenskit/cli/__init__.py
  src/lenskit/logging/config.py
  src/lenskit/logging/processors.py
  src/lenskit/logging/progress/_base.py
  src/lenskit/logging/progress/_notebook.py
  src/lenskit/logging/progress/_rich.py
Labels: internals

#682 Update FlexMF parameters to better defaults
  src/lenskit/flexmf/_base.py
  tests/flexmf/test_flexmf_implicit.py
Labels: components
