Repository lenskit/lkpy, pull requests merged in 2025-05, with the labels that each got.

#744 Add configurable weighting models
  src/lenskit/metrics/__init__.py
  src/lenskit/metrics/ranking/__init__.py
  src/lenskit/metrics/ranking/_dcg.py
  src/lenskit/metrics/ranking/_rbp.py
  src/lenskit/metrics/ranking/_weighting.py
  tests/eval/test_rank_ndcg.py
  tests/eval/test_rank_rbp.py
Labels: evaluation

#748 Test and fix crash on Linux ARM
  .github/workflows/test.yml
  src/accel/atomic.rs
  tasks.py
Labels: build

#749 Update ALS solve to zero rows for no-info users/items
  src/accel/als/explicit.rs
  src/accel/als/implicit.rs
Labels: components

#751 Add importers for UCSD Amazon data
  .github/workflows/test.yml
  data/.gitignore
  docs/guide/data/amazon.rst
  docs/guide/data/datasets.rst
  src/lenskit/cli/data/convert.py
  src/lenskit/cli/data/describe.py
  src/lenskit/cli/data/fetch.py
  src/lenskit/data/__init__.py
  src/lenskit/data/amazon.py
  src/lenskit/data/relationships.py
  tests/data/test_load_amazon.py
Labels: data

#741 Add sklearn NMF as a scorer
  src/lenskit/sklearn/nmf.py
  src/lenskit/sklearn/svd.py
  tests/sklearn/test_nmf.py
Labels: components

#755 Add Gini coefficient metrics
  docs/api/metrics.rst
  src/lenskit/metrics/__init__.py
  src/lenskit/metrics/_base.py
  src/lenskit/metrics/ranking/__init__.py
  src/lenskit/metrics/ranking/_base.py
  src/lenskit/metrics/ranking/_gini.py
  src/lenskit/metrics/ranking/_pop.py
  src/lenskit/testing/__init__.py
  src/lenskit/testing/_movielens.py
  tests/eval/test_gini.py
  tests/eval/test_rank_popularity.py
Labels: evaluation

#758 Add ItemList.top_n and speed up ItemList operations
  conftest.py
  pyproject.toml
  src/accel/als/explicit.rs
  src/accel/data/mod.rs
  src/accel/data/selection.rs
  src/accel/data/sorting.rs
  src/lenskit/_accel.pyi
  src/lenskit/basic/candidates.py
  src/lenskit/basic/topn.py
  src/lenskit/data/arrow.py
  src/lenskit/data/checks.py
  src/lenskit/data/collection/_base.py
  src/lenskit/data/collection/_list.py
  src/lenskit/data/items.py
  src/lenskit/data/mtarray.py
  src/lenskit/data/vocab.py
  src/lenskit/flexmf/_base.py
  src/lenskit/stats.py
  src/lenskit/stochastic/_ranker.py
  tasks.py
  tests/accel/test_accel_neg_mask.py
  tests/benchmarks/benchmark_il_take.py
  tests/benchmarks/benchmark_index.py
  tests/benchmarks/benchmark_isin.py
  tests/benchmarks/benchmark_remove.py
  tests/benchmarks/benchmark_topn.py
  tests/benchmarks/benchmark_weighting.py
  tests/data/test_arrow_util.py
  tests/data/test_collection.py
  tests/data/test_data_compat.py
  tests/data/test_itemlist.py
  tests/data/test_itemlist_topn.py
  uv.lock
Labels: batch, performance

#763 Add a rate limiter and use ray.wait to manage Ray concurrency
  src/lenskit/parallel/ray.py
  tests/parallel/test_ray_utils.py
  uv.lock
Labels: internals

#764 Switch back to Just + docopt
  .github/workflows/conda.yml
  .github/workflows/package.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  justfile
  pyproject.toml
  tasks.py
  utils/update-headers.py
  utils/version-tool.py
  uv.lock
Labels: internals

#774 Force Python UTF-8 mode for license hader update in pre-commit
  .pre-commit-config.yaml
Labels: build

#783 Use pytest-retry to retry the flaky stochastic ranker test
  pyproject.toml
  tests/stochastic/test_stochastic_ranker.py
  uv.lock
Labels: build

#782 Add component input hooks to the pipeline
  docs/api/pipeline.rst
  docs/guide/pipeline.rst
  docs/releases/2025.rst
  src/lenskit/pipeline/__init__.py
  src/lenskit/pipeline/_hooks/__init__.py
  src/lenskit/pipeline/_hooks/typecheck.py
  src/lenskit/pipeline/_impl.py
  src/lenskit/pipeline/builder.py
  src/lenskit/pipeline/config.py
  src/lenskit/pipeline/runner.py
  src/lenskit/pipeline/types.py
  tests/pipeline/test_component_input_hook.py
  tests/pipeline/test_fallback.py
  tests/pipeline/test_modify_pipeline.py
  tests/pipeline/test_pipeline.py
  tests/pipeline/test_pipeline_runtime_typecheck.py
Labels: pipeline
